### ISSUE TITLE
Splitter splits every split when grabbing 100 coin stars (US)

### ISSUE THREAD

**Issue by Malkierian** [fmichea/sm64-livesplit-autosplitter#10]
I just barely downloaded the release from like 9 hours ago, and on my first 70 star run (US version obviously, I haven't tested this with JP), no matter which split is active (including Bowser ones) or which 100 coin star I get, getting the star will immediately split every split on the list. I tested this with WF, CCM and JRB 100 coin stars. It continues trying too, as long as you're in xcam (meaning you can't undo them until you're moving again). Video shows example of it happening (you can also see how my splits are named, in case that makes a difference).

https://youtu.be/jm5_Q69nFEQ

**Comment by fmichea** [comment]
Made a new release v2.1.2 with fix released yesterday but without this side effect, please let me know if you run into this again (I tried a few combinations of 100 coins which worked as expected for me)

edit: And once again, big apologies on this one, this is quite a terrible mistake.
