### ISSUE TITLE
Split Stage RTA Functionality

### ISSUE THREAD

**Issue by Malkierian** [fmichea/sm64-livesplit-autosplitter#20]
Right now, the instructions for stage RTA include using banned codes in Usamune. Whatever functionality it has should probably be split so that leaderboard RTA and segmented run RTA practice are separate functions that work within their intended scopes.

**Comment by fmichea** [comment]
Forgot to update, but a new version was made to support normal way to do stage rtas (I hope I remembered to send it to you during league), and it has been merged since into main branch. Should solve this issue!
