### ISSUE TITLE
[Request] Add file delete on reset

### ISSUE THREAD

**Issue by Malkierian** [fmichea/sm64-livesplit-autosplitter#8]
Unfortunately I came here from aglab's splitters, and they had the option to delete save file A on reset, and I got used to that (though I try to continue without saving as often as possible, I slip up from time to time), so I was hoping I could get you to add that functionality into yours.

**Comment by fmichea** [comment]
Hey @Malkierian, thanks for the request!

I originally wanted to add this feature as well but after putting quite a bit of thought into it, I believe this will unfortunately not be part of this auto splitter. I totally get the quality of life this brings, but it raises a more difficult question for me: run validity.

For run verification, it is asked that run be played on an unmodified vanilla rom using a specific version of the emulator. The way this feature works is by modifying the RAM of the game after the run has started (it zeroes a section of memory related to save files until the timer reaches 4 seconds).

When considering this, I think this makes runs played with this feature on technically invalid. Similar to having a gameshark on or similar. I do not think it is likely to be enforced but I also do not want to introduce this into the auto splitter:

  - It would be difficult for me to verify that the only side effect of zero'ing this part of the memory is remove the save file.
  - It would be difficult to justify how features that modify the RAM are picked (what's OK, what's not OK).
  - I would hate for runs done with this auto splitter on to be questioned in the future.

For those reasons, I think this will only ever do reads of the memory, no modification. Does that make sense?

**Comment by Malkierian** [comment]
I can understand your reasoning, though I feel that could be addressed by an explicit warning in several places that enabling it _could_ invalidate runs should a decision be made later on. Or, get an official decision from the mods on the subject now so we could know one way or the other. Perhaps, if you do it in a certain way, they could allow it for your splitter specifically? Since it only affects emulator runners anyway, and doesn't affect the run itself, including the intro, I feel like there's a good possibility they'd allow it.

**Comment by fmichea** [comment]
I talked with the moderation team before commenting and they concurred that modifying RAM would not be OK as far as the rules for run submission go. Basically any modification after the run has started would be a no go.

It would pretty much be impossible to certify that a change does not have any side effect that makes the game faster in any way. As an alternative they mentioned having a keyboard macro which could delete the emulator save file _then_ reset the emulator, or having a save state with no save file which would be loaded _before_ reset. That would be OK by the rules. That's not something the splitter could do.

I understand I could label the option "cheating mode" but at this point it might make more sense for this to be documented/provided another way. I don't think it fits that well into the scope of the auto splitter.

I hope you can understand my position, I'm sorry I couldn't accommodate the request. Please feel free to comment and re-open if anything could change this.

**Comment by Malkierian** [comment]
Actually, I've tried the save state idea. It doesn't work, because save states only handle RAM. Upon reset, it reloads the save files. If they would let us run intro skip on emulator, then that would work, but we all know that's never happening. I'll give actual file deletion idea a try.
